#print("Hola Mundo")

#print("hola" " " "Fede")
#print("Me llamo \"Federico\"")
#print("Esta es una línea\n Y esta es otra línea")
#print("\t Esta es la tercera línea")
#print("Este signo \\ una barra invertida")
#print("línea 1\nlínea 2\nlínea 3")
#print("A\t B\t C")
#print("D\t E\t F")
#print("G\t H\t I")
#print("Barra Normal:/\nBarra Invertida:\\")
#print("Tu nombre es "+ input("Cuál es tu nombre? ") + " " + input("Cuál es tu apellido: "))
#print(input("Escribe tu nombre: ") +" "+ input("Escribe tu apellido: "))

